### ISSUE TITLE
Could not parse `-/metadata.rb': undefined method `chef_version'

### ISSUE THREAD

**Issue by gowthamgts** [sous-chefs/rvm#384]
### :speaking_head: Foreword

We're using AWS opsworks and we're unable to run setup since we're getting the following error:

```Ridley::Errors::FromFileParserError: Could not parse `/tmp/d20191015-3355-hr01dz/metadata.rb': undefined method `chef_version' for #<Ridley::Chef::Cookbook::Metadata:0x00558137e94ce8>```

## :ghost: Brief Description

It looks like the bug has been introduced with #382.

## :woman_cook:  Chef-Infra Version

11.10 (Berkshelf: 3.2.0)

## :tophat: Platform details

AWS Opsworks

## Steps To Reproduce

Create a new instance under Opsworks with berkshelf enabled

## :police_car: Expected behavior

Instance should run setup successfully.

**Comment by damacus** [comment]
Hi!

thanks for raising this issue. We no longer support Chef 11, see the [Chef versions](https://docs.chef.io/versions.html) page for the supported Chef versions.

**Comment by gowthamgts** [comment]
@damacus: Thanks, we're now using the `0.9.4` instead of `master`.
